"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# Yazi keymaps

# KEYBOARD-LAYOUT
#
#   ` 1 2 3 4 5 6 7 8 9 0 - =
#   ~ ! @ # $ % ^ & * ( ) _ +
#
#   Q W E R T Y U I O P [ ] \
#   q w e r t y u i o p { } |
#
#   A S D F G H J K L ; '
#   a s d f g h j k l : "
#
#   Z X C V B N M , . /
#   z x c v b n m < > ?

[[input.prepend_keymap]]
on   = [ '*' ]
run = "select_all --state=true"
desc = "Select all"

[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on   = [ "i" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = [ "l" ]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on  = [ "<Tab>" ]
run = "plugin --sync max-preview"
