#!/usr/bin/env bash
# bash/exports
# ---
# github.com/rafi/.config

export LANG="en_US.UTF-8"
export LC_CTYPE="$LANG"
export LC_ALL="$LANG"

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export  XDG_CACHE_HOME="$HOME/.cache"
export   XDG_DATA_HOME="$HOME/.local/share"
export  XDG_STATE_HOME="$HOME/.local/state"

[ -d "$XDG_CONFIG_HOME" ] || mkdir -m 0750 "$XDG_CONFIG_HOME"
[ -d "$XDG_CACHE_HOME" ]  || mkdir -m 0750 "$XDG_CACHE_HOME"
[ -d "$XDG_DATA_HOME" ]   || mkdir -m 0750 "$XDG_DATA_HOME"
[ -d "$XDG_STATE_HOME" ]  || mkdir -m 0750 "$XDG_STATE_HOME"

# terminfo in config home.
if [ -d "$XDG_CONFIG_HOME/terminfo" ]; then
	export TERMINFO="$XDG_CONFIG_HOME/terminfo"
fi

# Source .env file is exists
[ -f "$XDG_CONFIG_HOME/.env" ] && source "$XDG_CONFIG_HOME/.env"

# Local bin
PATH="$HOME/.local/bin:$PATH:bin"

# History settings
export HISTSIZE=20000
if [ "$BASH" ]; then
	export HISTFILE="$XDG_CACHE_HOME/bash_history"
	export HISTFILESIZE=15000000
	export HISTTIMEFORMAT='[%F %T] '
	export HISTIGNORE='pwd:jobs:ll:ls:l:history:c:clear'
	export HISTCONTROL=ignoreboth
	# export HISTCONTROL='ignoreboth:erasedups'
	# Append to history and set the window title as 'user@host:dir'
	# export PROMPT_COMMAND="history -a; ${PROMPT_COMMAND}"
	# export PROMPT_COMMAND='history -a; echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
elif [ "$ZSH_VERSION" ]; then
	export HISTFILE="${XDG_CACHE_HOME}/zsh_history"
	export SAVEHIST="${HISTSIZE}"
fi

# Append to history and set the window title
# export PROMPT_COMMAND='history -a; echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
export PROMPT_COMMAND='history -a; printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"'

# Editor and manpager
# ----
EDITOR=vim
if hash nvim 2>/dev/null; then
	export MANPAGER="nvim +'set cmdheight=2' +Man!"
	EDITOR=nvim
fi
export EDITOR
export VISUAL="$EDITOR"

export PAGER=less
export LESS="-FiQMXR"
# export LESS="-FiQMXRW --incsearch"
export LESSCHARSET="UTF-8"
export LESSHISTFILE="$XDG_CACHE_HOME/less_history"
# On newer versions of less, use the following to support Nerdfonts.
export LESSUTFCHARDEF="E000-F8FF:p,F0000-FFFFD:p,100000-10FFFD:p"

# Finders
# ----

# Ripgrep https://github.com/BurntSushi/ripgrep
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/rc"

export FZF_DEFAULT_OPTS="--margin 1,5% --border --info=inline-right --separator --reverse --height 100% --bind=ctrl-d:page-down,ctrl-u:page-up,ctrl-y:yank,tab:down,btab:up"
export FZF_DEFAULT_COMMAND='rg --vimgrep --files --follow --hidden --no-ignore-vcs --smart-case --glob !**/.git/*'

# vim: set ft=sh ts=2 sw=2 tw=80 noet :
