# starship configuration
# ---
# see https://starship.rs/config/

add_newline = false

[hostname]
ssh_only = false

[line_break]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true

[terraform]
disabled = true

[rust]
disabled = true
