# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# ship configuration
# ---
# see https://starship.rs/config/

add_newline = false

format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$git_status\
$shell\
$character"""

[battery]
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
unknown_symbol = '󰂑 '
empty_symbol = '󰂎 '

[container]
symbol = ' '

[character]
success_symbol = '[λ](green):'
error_symbol = '[x](red)'

[cmd_duration]
min_time = 2500
format = ' [⏱ $duration]($style) '

[directory]
format = '[$path/]($style)[$read_only]($read_only_style)'
read_only = ' 󰌾'
style = 'blue'
truncation_length = 4

[git_branch]
format = '([$symbol](fg:8)[$branch]($style)([:$remote_branch](fg:243)) )'
symbol = ' '
# symbol = ''
style = 'green'

[git_commit]
tag_symbol = '  '

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[username]
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']

[hostname]
ssh_only = true
ssh_symbol = ' '
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']

[memory_usage]
symbol = '󰍛 '

[shlvl]
symbol = '󰹍 '

[status]
symbol = ' '

[sudo]
symbol = ' '

[custom.yazi]
when = ''' test -n "$YAZI_LEVEL" '''
format = '\[[Yazi]($style)\] '
style = 'green'
